services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: "piseth@12345"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "product-service"
    ports:
      - "2345:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge