spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      routes:
        - id: productService
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AddRequestHeader=X-Request-Header,Product-Service Header
            - AddResponseHeader=Cache-Control, max-age=360, private
            - AddResponseHeader=X-Request-ID, ${random.uuid}        # Add unique request ID for tracing
            #            - AddResponseHeader=X-Timestamp, ${time.now}            # Add current timestamp
            - AddResponseHeader=X-Response-Header, Product-Service Header
    #            - SetResponseHeader=X-Response-Header-1, Product-Service Header
    #            - ModifyResponseHeader=X-Response-Header, 'Old-Value', 'New-Value'

    discovery:
      locator:
        lower-case-service-id: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE