server:
  port: 8082

spring:
  application:
    name: product-service

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:9090"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
#
#
#
